# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Upload artifact to snowsql
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
          ~/bin/snowsql -u ${{ secrets.SNOWFLAKE_USERNAME }} -a ${{ secrets.SNOWFLAKE_ACCOUNT }} -q 'put file://'$(pwd)'/_${{ github.ref_name }}/python.py @~ overwrite=true' -o friendly=false
        env:
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Create or update storedproc
        run: |
          ~/bin/snowsql -u ${{ secrets.SNOWFLAKE_USERNAME }} -a ${{ secrets.SNOWFLAKE_ACCOUNT }} -w SRI -d JEFFHOLLAN_DEMO -s PUBLIC -q 'CREATE OR REPLACE PROCEDURE PYPROC_${{ github.ref_name }}(from_table STRING, to_table STRING, count INT)
                                        RETURNS STRING
                                        LANGUAGE PYTHON
                                        RUNTIME_VERSION = '\''3.8'\''
                                        PACKAGES = ('\''snowflake-snowpark-python'\'')
                                        IMPORTS = ('\''@~/_${{ github.ref_name }}/python.py'\'')
                                        HANDLER = '\''python.run'\'';' -o friendly=false